### PR TITLE
feat(shields): Add dactyl shields

### PR DESCRIPTION
**Pull request by dunk2k**
## Board/Shield Check-list

- [ ] This board/shield is tested working on real hardware
- [x] Definitions follow the general style of other shields/boards upstream ([Reference](https://zmk.dev/docs/development/new-shield))
- [x] `.zmk.yml` metadata file added
- [x] Proper Copyright + License headers added to applicable files (Generally, we stick to "The ZMK Contributors" for copyrights to help avoid churn when files get edited)
- [ ] General consistent formatting of DeviceTree files
- [x] Keymaps do not use deprecated key defines (Check using the [upgrader tool](https://zmk.dev/docs/codes/keymap-upgrader))
- [x] `&pro_micro` used in favor of `&pro_micro_d/a` if applicable
- [x] If split, no name added for the right/peripheral half
- [ ] Kconfig.defconfig file correctly wraps _all_ configuration in conditional on the shield symbol
- [x] `.conf` file has optional extra features commented out
- [ ] Keyboard/PCB is part of a shipped group buy or is generally available in stock to purchase (OSH/personal projects without general availability should create a zmk-config repo instead)

### CODE REVIEW

**Comment by caksoylar** [comment]
I am not sure if it makes sense to include handwired keyboards (which these are, right?) in the main ZMK repo, since there is no standard on how a user is supposed to wire them (or is there?). If it is to be of any use, there needs to be extensive documentation on how everything is wired for these shields so the user can follow it. But I don't like that idea very much either.

Ideally our new shield documentation would be straightforward enough for users to follow for bespoke handwired keyboards. Another thing that would help is a ZMK CLI #34 with a `new-keyboard` command to output a boilerplate, or prompt the user for pin assignments and optional features.

**Comment by dunk2k** [comment]
> I am not sure if it makes sense to include handwired keyboards (which these are, right?) 

That's correct. If there was documentation to declare that handwired boards are not excepted, it would've spared me this effort.

> in the main ZMK repo, since there is no standard on how a user is supposed to wire them (or is there?). If it is to be of any use, there needs to be extensive documentation on how everything is wired for these shields so the user can follow it. But I don't like that idea very much either.

I can create wiring documentation for each shield, though it appears the effort might be wasted due to a clear indication of aversion. Were I to create a wiring diagram for each shield, and inadvertently set a presedence for handwired boards in ZMK, would this PR be approved?
i.e. Am I wasting my time putting any more effort into this?

**Comment by dunk2k** [comment]
> OSH/personal projects without general availability should create a zmk-config repo instead

I would ask for clarification of 'general availability'.  
If there was a clause that exclusively mentions, not infers, that handwired shields are not permitted due to specific reasons**, I'd of genuinely been averted from cresting this PR.

** - i deduce is because a handwired shield isn't strictly defined as a PCB design is; which is understandable, if it is a principle of the 'shield' concept/terminology.

> (Just to clarify, I am presenting my own opinions as a contributor here and not commenting in behalf of the project/maintainers.)

I appreciate the heads up, of what may to come 🙂

**Comment by dunk2k** [comment]
Closing based on review comments

**Pull request closed without merging**
