### PR TITLE
Tap or Hold behavior

### LINKED ISSUE #49: Feature: layer-tap behavior
Keymap feature that needs implementing: layer-tap.

A behavior that binds a key to momentary layer when held, or taps a key when tapped independently.

### PR DESCRIPTION
**Pull request by BrainWart**
I think this partially resolves #49. I have included docs with a few handy examples as well.

### CODE REVIEW

**Comment by tominabox1** [comment]
@BrainWart Have you tried with multiple tap-holds in one file? I have 3 defined in my keymap and it appears to apply the binding in the last definition to all of the defined behavior. 

`/ {
	behaviors {
		rst: behavior_tap_hold {
			compatible = "zmk,behavior-tap-hold";
			label = "Reset Tap - Bootloader Hold";
			#binding-cells = <0>;
			hold_ms = <200>;
			bindings = <&bootloader>, <&reset>, <&kp BKSP>;
        };

        num_spc: behavior_tap_hold {
			compatible = "zmk,behavior-tap-hold";
			label = "Space Tap - Num/Sym Hold";
			#binding-cells = <0>;
			hold_ms = <200>;
			bindings = <&kp SPC>, <&mo NUM_SYM>, <&kp BKSP>;
        };
    };
`

This code results in both &rst and &num_spc providing &kp SPC on tap and &mo NUM_SYM on hold.

**Comment by BrainWart** [comment]
> ```
> rst: behavior_tap_hold {
> num_spc: behavior_tap_hold {
> ```

So, it turns out the bit that defines if the section is a tap-hold behavior is the compatible key. Try:

```
rst: behavior_tap_hold1 {
num_spc: behavior_tap_hold2 {
```

**Comment by tominabox1** [comment]
Ah yes! This works as expected now, great.

**Comment by BrainWart** [comment]
Okke's PR #146 implements hold-tap behavior much nicer.

**Pull request closed without merging**
