### PR TITLE
refactor: align drivers with Zephyr file system conventions

### PR DESCRIPTION
**Pull request by innovaker**

### CODE REVIEW

**Comment by innovaker** [comment]
Rebased and tested e2e:
- [e2e-2020-12-03T14-59-38-ble.log](https://github.com/zmkfirmware/zmk/files/5636923/e2e-2020-12-03T14-59-38-ble.log)
- [e2e-2020-12-03T14-59-38-usb.log](https://github.com/zmkfirmware/zmk/files/5636924/e2e-2020-12-03T14-59-38-usb.log)

**Comment by innovaker** [comment]
This PR would probably benefit from closer scrutiny.  I based what appears to be Zephyr's standard approach.

**Comment by innovaker** [comment]
I've also tested this merged with #406.

**Review by petejohanson — APPROVED** [review]
LGTM!

**Pull request merged**
