### PR TITLE
Fix battery charge icon out of screen boundary

### PR DESCRIPTION
**Pull request by WSTRN**

### CODE REVIEW

**Comment by petejohanson** [comment]
Can you get some pictures of the before and after here? I'd never noticed it truncating.

**Comment by WSTRN** [comment]
> Can you get some pictures of the before and after here? I'd never noticed it truncating.

Sorry, I didn't take the previous photos. The part I circled up outside the screen, about two or three pixels. This problem may occur after the Bluetooth icon shows that the connection is successful.
I just expanded the icon display area, and I don't think it's the best solution.

37257F73-463E-419D-8F31-F2DBAA2F95EF
5CFA65A9-3758-4DAC-B288-6532848B009C
F3A101FA-B3BC-47E1-86BA-509A72662268

**Comment by WSTRN** [comment]
I use this screen.
7799A8DC-8094-4074-B498-5569496A4B6B

**Comment by petejohanson** [comment]
Thanks! Makes sense to me.

**Review by petejohanson — APPROVED** [review]

**Pull request merged**
