### PR TITLE
Add missing licensing header

### LINKED ISSUE #205: Add missing headers
Some existing files are missing their copyright/licensing header.

The basic template for *.c and *.h files is:
```
/*
 * Copyright (c) 2020 The ZMK Contributors
 *
 * SPDX-License-Identifier: MIT
 */
```

Clearing this up is a prerequisite for #38.

### PR DESCRIPTION
**Pull request by DevMashru**
Fix #205

### CODE REVIEW

**Review by innovaker — APPROVED** [review]
Thanks @DevMashru!

I flicked through the project and confirmed this covers all the `.h` and `.c` files with missing headers.

LGTM.

**Comment by innovaker** [comment]
@petejohanson, on my travels I noticed two BT related files with:
`Copyright (c) 2020 Peter Johanson <peter@peterjohanson.com>`
but I wasn't sure if they were intentional?

**Comment by petejohanson** [comment]
> @petejohanson, on my travels I noticed two BT related files with:
> `Copyright (c) 2020 Peter Johanson <peter@peterjohanson.com>`
> but I wasn't sure if they were intentional?

Nope. Should get zapped.

**Comment by innovaker** [comment]
Could we please merge this now?  I'd prefer to rebase on top of it before pushing out #21's draft.

**Review by petejohanson — APPROVED** [review]
LGTM! Thanks.

**Pull request merged**
