### PR TITLE
refactor(docs): Bump to docusaurus 2.0.0-beta.18

### PR DESCRIPTION
**Pull request by petejohanson**
* Fix up the config to use proper locations.

### CODE REVIEW

**Comment by dxmh** [comment]
https://deploy-preview-1216--zmk.netlify.app/docs

One of the changes I notice in the docs preview for this PR is a breadcrumb trail at the top of each page (added and enabled by default in beta 16 it seems):

Screenshot 2022-04-05 at 9 10 07 pm

I think this is nice in theory, however in practice there's a couple of things which aren't ideal out-of-the-box:

1. Clicking "🏠" goes to https://zmk.dev rather than https://zmk.dev/docs
2. We don't have pages for the top level items – you can't click "Behaviours" in the above screenshot for example (somewhat related: https://github.com/zmkfirmware/zmk/issues/525)

I think we could consider [disabling the breadcrumb](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#breadcrumbs) or look at possibly restructuring a few things to make it more useful.

**Comment by petejohanson** [comment]
> https://deploy-preview-1216--zmk.netlify.app/docs
> 
> One of the changes I notice in the docs preview for this PR is a breadcrumb trail at the top of each page (added and enabled by default in beta 16 it seems):
> 
> Screenshot 2022-04-05 at 9 10 07 pm
> 
> I think this is nice in theory, however in practice there's a couple of things which aren't ideal out-of-the-box:
> 
>     1. Clicking "house" goes to https://zmk.dev rather than https://zmk.dev/docs
> 
>     2. We don't have pages for the top level items – you can't click "Behaviors" in the above screenshot for example (somewhat related: [Add "Overview" page as the first link under "Behaviors" in docs #525](https://github.com/zmkfirmware/zmk/issues/525))
> 
> 
> I think we could consider [disabling the breadcrumb](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#breadcrumbs) or look at possibly restructuring a few things to make it more useful.

Good catch! I would vote for removing, since the current structure doesn't make them particularly useful. Any objections?

**Comment by dxmh** [comment]
Looking through the [Docusaurus changelog](https://docusaurus.io/changelog), I see there were various changes between beta 3 and beta 18 that touch algolia (search).

Search doesn't seem to work on the preview for this PR:

image

Same search performed on the [live docs](https://zmk.dev/docs), or in [other PR previews](https://deploy-preview-722--zmk.netlify.app/docs/):

image

I'm not sure what the cause is (I should be able to review the changelog a bit more thoroughly in the next day or so), but I wanted to mention this before it gets merged.

**Comment by petejohanson** [comment]
> Looking through the [Docusaurus changelog](https://docusaurus.io/changelog), I see there were various changes between beta 3 and beta 18 that touch algolia (search).
> 
> Search doesn't seem to work on the preview for this PR:
> 
> image
> 
> Same search performed on the [live docs](https://zmk.dev/docs), or in [other PR previews](https://deploy-preview-722--zmk.netlify.app/docs/):
> 
> image
> 
> I'm not sure what the cause is (I should be able to review the changelog a bit more thoroughly in the next day or so), but I wanted to mention this before it gets merged.

Yeah, I *suspect* the new app hasn't indexed yet, but let me investigate more what might be needed for setup on the Algolia side.

**Comment by petejohanson** [comment]
Found the new API key they emailed me, just pushed w/ the new value, we can see if that works now.

**Comment by joelspadin** [comment]
> > https://deploy-preview-1216--zmk.netlify.app/docs
> > One of the changes I notice in the docs preview for this PR is a breadcrumb trail at the top of each page (added and enabled by default in beta 16 it seems):
> > Screenshot 2022-04-05 at 9 10 07 pm
> > I think this is nice in theory, however in practice there's a couple of things which aren't ideal out-of-the-box:
> > ```
> > 1. Clicking "house" goes to https://zmk.dev rather than https://zmk.dev/docs
> > 
> > 2. We don't have pages for the top level items – you can't click "Behaviors" in the above screenshot for example (somewhat related: [Add "Overview" page as the first link under "Behaviors" in docs #525](https://github.com/zmkfirmware/zmk/issues/525))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think we could consider [disabling the breadcrumb](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#breadcrumbs) or look at possibly restructuring a few things to make it more useful.
> 
> Good catch! I would vote for removing, since the current structure doesn't make them particularly useful. Any objections?

Maybe we could add pages for each category which give a brief overview (e.g. explain what a "behavior" is)? I would say that isn't related to bringing up docusaurus though, and should be done in a separate change.

**Comment by petejohanson** [comment]
Doc search seems to be working fine with the updated appId and apiKey. Pushed a change to remove the breadcrumbs (for now).

**Comment by dxmh** [comment]
> Maybe we could add pages for each category which give a brief overview (e.g. explain what a "behavior" is)? I would say that isn't related to bringing up docusaurus though, and should be done in a separate change.

I think this is a good idea for a separate PR.

Here's a couple of issues somewhat related to this:

* https://github.com/zmkfirmware/zmk/issues/793
* https://github.com/zmkfirmware/zmk/issues/525

**Review by dxmh — APPROVED** [review]
> Doc search seems to be working fine with the updated appId and apiKey. Pushed a change to remove the breadcrumbs (for now).

Yep. The updated site seems good to me now.

**Pull request merged**
