### PR TITLE
feat: Add Osprette Shield

### PR DESCRIPTION
**Pull request by smores56**
## Board/Shield Check-list
 - [x] This board/shield is tested working on real hardware
 - [x] Definitions follow the general style of other shields/boards upstream ([Reference](https://zmk.dev/docs/development/new-shield))
 - [x] `.zmk.yml` metadata file added
 - [x] Proper Copyright + License headers added to applicable files
 - [x] General consistent formatting of DeviceTree files
 - [x] Keymaps do not use deprecated key defines (Check using the [upgrader tool](https://zmk.dev/docs/codes/keymap-upgrader))
 - [x] `&pro_micro` used in favor of `&pro_micro_d/a` if applicable
 - [x] If split, no name added for the right/peripheral half
 - [x] `.conf` file has optional extra features commented out

### CODE REVIEW

**Comment by smores56** [comment]
> Is there a group buy or general availability planned, or is this strictly OSH at the moment?

Even though there is a GB happening for the board, it is simultaneously fully OSH, including the PCB and the case. https://github.com/smores56/osprette

**Comment by Nicell** [comment]
> Even though there is a GB happening for the board at smoresboards.com, it is simultaneously fully OSH, including the PCB and the case. https://github.com/smores56/osprette

Awesome! Generally, we'd like to wait to merge until the GB has closed and is in production.

**Comment by smores56** [comment]
> Awesome! Generally, we'd like to wait to merge until the GB has closed and is in production.

Ok, I'll ping this when the GB is closed and begins production.

**Comment by smores56** [comment]
@Nicell the GB is finished and people have begun to receive their boards. Can we merge this?

**Pull request merged**
