### PR TITLE
Fix minor Reviung41 layout errors, setup OLED display

### PR DESCRIPTION
**Pull request by GerardoNevarez**
This fixes some layout errors, compared to the original Reviung41 firmware.

Also sets up the OLED display for PCBs that added support for them (i.q. wsk)

### CODE REVIEW

**Comment by TahuTech** [comment]
> 

hello, how to install  the oled in original pcb ?

**Comment by GerardoNevarez** [comment]
I bought the PCB from World Span Keyboards... their modified PCB has not
been published as Open Source Hardware, AFAIK.

if you do bodge wires to the common promicro i2c , should work, but you
need to figure out how to mount it.

**Comment by TahuTech** [comment]
thanks for the explanation

**Comment by GerardoNevarez** [comment]
This was done over 2 years ago, no longer pursuing this PR. Closing it.

**Pull request closed without merging**
