### PR TITLE
Update setup.md

### PR DESCRIPTION
**Pull request by Huckies**
docs: Switching from gcc-arm-embedded to arm-none-eabi-gcc as well as adding two environment variables to fix a possible compatibility problem on macOS.

### CODE REVIEW

**Comment by dxmh** [comment]
Somewhat related PR: 

* https://github.com/zmkfirmware/zmk/pull/917

**Comment by caksoylar** [comment]
Can anybody test this on Mac OS and confirm if this needs to be updated?

**Comment by flink-sdg** [comment]
I tested this.  It worked for the most part for me.

The one thing I had to change was the toolchain path.  For me, it was:

GNUARMEMB_TOOLCHAIN_PATH=/usr/local/cellar/arm-none-eabi-gcc/10.3-2021.07/gcc

**Comment by Huckies** [comment]
> I tested this. It worked for the most part for me.
> 
> The one thing I had to change was the toolchain path. For me, it was:
> 
> GNUARMEMB_TOOLCHAIN_PATH=/usr/local/cellar/arm-none-eabi-gcc/10.3-2021.07/gcc
> 
> That aside, this was extremely helpful!

Thanks for pointing it out, are you using an Intel Mac?

**Comment by flink-sdg** [comment]
> 

I am, yes.

Intel, i-9

macOS Monterey 12.3.1

**Comment by Huckies** [comment]
> I am, yes.
> 
> Intel, i-9
> 
> macOS Monterey 12.3.1

That's an unexpected situation as I have been using Apple Silicon for quite some time. It's now fixed with a little trick

**Comment by Huckies** [comment]
> I am, yes.
> 
> Intel, i-9
> 
> macOS Monterey 12.3.1

That's an unanticipated situation as I have been using Apple Silicon for quite some time. It's now fixed with a little trick.

**Pull request closed without merging**
