### PR TITLE
feat(shields): Add Kyria Rev2 shield.

### PR DESCRIPTION
**Pull request by petejohanson**
* New matrix pin selections.
* New encoder pins.

## Board/Shield Check-list
 - [x] This board/shield is tested working on real hardware
 - [x] Definitions follow the general style of other shields/boards upstream ([Reference](https://zmk.dev/docs/development/new-shield))
 - [x] `.zmk.yml` metadata file added
 - [x] Proper Copyright + License headers added to applicable files (Generally, we stick to "The ZMK Contributors" for copyrights to help avoid churn when files get edited)
 - [x] General consistent formatting of DeviceTree files
 - [ ] Keymaps do not use deprecated key defines (Check using the [upgrader tool](https://zmk.dev/docs/codes/keymap-upgrader))
 - [x] `&pro_micro` used in favor of `&pro_micro_d/a` if applicable
 - [x] If split, no name added for the right/peripheral half
 - [x] Kconfig.defconfig file correctly wraps *all* configuration in conditional on the shield symbol
 - [x] `.conf` file has optional extra features commented out
 - [x] Keyboard/PCB is part of a shipped group buy or is generally available in stock to purchase (OSH/personal projects without general availability should create a zmk-config repo instead)

### CODE REVIEW

**Comment by petejohanson** [comment]
@Nicell Seems like changes picked up, but didn't build the `kyria_rev2*` stuff.... tweaks needed to new change detection.

**Comment by petejohanson** [comment]
I don't have test hardware, so waiting on testing from splitkb folks.

**Comment by Nicell** [comment]
It does seem to be picking up the file changes, but for some reason, the `board-changes` run isn't outputting the `kyria_rev2_left/right`. Even the `get-grouped-hardware` has the rev2 in it.
image

I'll try to take a look tomorrow. Really strange, I haven't tested new shield revisions, so maybe there's some issue with picking up multiple `.zmk.yml` files in the same folder.

**Comment by maxhbr** [comment]
I am trying to get this running in https://github.com/maxhbr/mykyria/tree/main/config, but on both sides MX25 does not work.

I even have the following weird behavior:
If I bind `&kp RALT` to the MX25 on the right side, that modifier is pushed constantly as soon as I push any key on the right side.

**Comment by petejohanson** [comment]
> I am trying to get this running in https://github.com/maxhbr/mykyria/tree/main/config, but on both sides MX25 does not work.
> 
> I even have the following weird behavior:
> If I bind `&kp RALT` to the MX25 on the right side, that modifier is pushed constantly as soon as I push any key on the right side.

I have some local fixes for this after Leah did some testing for me.

Will try to get pushed tonight.

**Comment by petejohanson** [comment]
@maxhbr Give it another try, just pushed the fixes. 

Thanks!

**Comment by maxhbr** [comment]
MX25 is now working (on left side, will test right next)

**Comment by maxhbr** [comment]
@kraklin You do not need to fork, i am referencing this PR directly via the following snippet:
    npm-Library, die plötzlich nicht mehr da war
        mimetypes - war plötzlich weg - wegen lizenzrechtlichen Problemen

**Comment by kraklin** [comment]
@maxhbr strange, I tried the change you suggested with the stock keymap, but it didn't work... Then I tried firmware of yours and that worked like a charm... something is off in my setup at https://github.com/kraklin/zmk-config - any clue? (I'm using ZMK for the first time, so sorry for maybe stupid question)

**Comment by maxhbr** [comment]
Yes, I think @caksoylar is right

**Comment by petejohanson** [comment]
> MX25 is now working (on left side, will test right next)
> 

@maxhbr is this verified working?

I need to verify the refactors on my rev1 Kyria, then once rev2 is confirmed, I'll merge.

**Comment by maxhbr** [comment]
My Kyria v2.0 is working with the firmware from https://github.com/maxhbr/mykyria/ without any issues. All keys are working. But I did not test the encoder or i2c.

**Comment by maxhbr** [comment]
FYI: just soldered encoders to my Kyria v2 but I can not get them to work.

**Pull request merged**
