### PR TITLE
improvement: upgrade default keymaps

### PR DESCRIPTION
**Pull request by joelspadin**
Ran all the default keymaps through the keymap upgrader and manually adjusted alignment.

### CODE REVIEW

**Comment by innovaker** [comment]
Amazing @joelspadin, above and beyond there!  Thank you for doing this 🥇

**Review by petejohanson — APPROVED** [review]
Rock on!

**Comment by petejohanson** [comment]
@innovaker feel free to merge after reviewing. Thanks!

**Comment by tominabox1** [comment]
Thanks for taking care of this! Consider this my approval for the QAZ default map

**Comment by innovaker** [comment]
Sorry this has taken me a while to get onto @joelspadin.  It's now my top priority.

To cover all bases, I'm enhancing the current CI build system because it was missing some boards and shields that should probably have coverage for a refactor as broad as this.  Once that's done and merged, I'll ask you to rebase the PR so that CI can do the heavy lifting.

I'm using this PR as the basis for the final green light of #344.  Admittedly I should've got these over the line sooner.

**Comment by innovaker** [comment]
@joelspadin, just spotted that the boards aren't included in this PR.  Was that intentional?

**Comment by joelspadin** [comment]
Whoops. No. I forgot there could be keymaps in the boards directory.

**Comment by joelspadin** [comment]
Updated the two keymaps in the boards directory.

**Comment by innovaker** [comment]
Thanks for adding those boards @joelspadin!  CI is now running a full deck also.

Please could you rebase onto `HEAD` for its final test run?  I've tested all the build combinations without the deprecated codes included on my personal account, so I expect all the tests to pass after the rebase.  I'll then get this and #344 merged.

**Comment by joelspadin** [comment]
Rebased.

**Comment by innovaker** [comment]
I've reconfirmed the previous test results with: https://github.com/innovaker/zmk/actions/runs/412903242

**Comment by innovaker** [comment]
Thanks a lot @joelspadin!  Great job 🥇

**Pull request merged**
