### PR TITLE
feat(boards): add Bluemacro840 board

### PR DESCRIPTION
**Pull request by 310weber**
**feat:** add support for BlueMacro840 board as "bluemacro840_v1"

* reference (http://nrf52.jpconstantineau.com/docs/bluemacro840_v1/).
* Board is similar to BlueMicro840 but has more GPIO pins available, and does not follow the ProMicro pinout.

* **Testing**
  * **Pass:** Test compile using "m60" shield.  Output to .uf2 file.
  * **Pass:** Load test zmk.uf2 to BlueMacro840 board (Adafruit bootloader).  Drag-and-drop in Windows file manager.
  * **Pass:** Connect to Windows computer over USB and Bluetooth.
  * **Untested:** I do not have a functional shield to test with yet to confirm keyboard function.

### CODE REVIEW

**Comment by 310weber** [comment]
Looking through the build errors it looks like they are all related to missing pro_micro references.  Is this expected since the board I'm adding doesn't share the pro_micro form factor and pinout?

Common error messages:
  - `ERROR (phandle_references): /kscan: Reference to non-existent node or label "pro_micro_a"`
  - `ERROR (phandle_references): /kscan: Reference to non-existent node or label "pro_micro_d"`
  - `Label or path pro_micro_i2c not found`

**Comment by Nicell** [comment]
> Looking through the build errors it looks like they are all related to missing pro_micro references. Is this expected since the board I'm adding doesn't share the pro_micro form factor and pinout?

Our build script currently only tests Pro Micro board/shield pairings in the matrix. This board shouldn't be added to the same matrix since it doesn't fit in it. An explicit pairing should probably be added in the `include` section, although I don't know of any shield that goes with this board currently?

**Comment by 310weber** [comment]
> > Looking through the build errors it looks like they are all related to missing pro_micro references. Is this expected since the board I'm adding doesn't share the pro_micro form factor and pinout?
> 
> Our build script currently only tests Pro Micro board/shield pairings in the matrix. This board shouldn't be added to the same matrix since it doesn't fit in it. An explicit pairing should probably be added in the `include` section, although I don't know of any shield that goes with this board currently?

Not that I'm aware of.  I'm working on hand wiring my own.

**Comment by 310weber** [comment]
> Our build script currently only tests Pro Micro board/shield pairings in the matrix. This board shouldn't be added to the same matrix since it doesn't fit in it. An explicit pairing should probably be added in the `include` section, although I don't know of any shield that goes with this board currently?

@Nicell - I added a commit moving the Bluemacro from the board/shield pairing matrix to the explicit includes section.  It is currently not paired with any shields but there are other examples like that so I assume it's ok.  Hopefully this cleans it up for anyone using this PR prior to the new board/shield system being implemented.

**Comment by petejohanson** [comment]
@310weber Are you still interested in getting this in? Needs an updated metadata file and build tweaks at least.

**Comment by 310weber** [comment]
@petejohanson Based on the lack of BlueMacro discussion on the Discord I'm guessing that not many other people are using it.  I'd be ok to close this PR and just maintain support in my own zmk-config repo if that's preferred to minimize maintenance overhead in the main codebase.

**Comment by petejohanson** [comment]
> @petejohanson Based on the lack of BlueMacro discussion on the Discord I'm guessing that not many other people are using it.  I'd be ok to close this PR and just maintain support in my own zmk-config repo if that's preferred to minimize maintenance overhead in the main codebase.

Yeah, seems fair to me. Happy to revisit if/when they become more popular.

**Pull request closed without merging**
