### PR TITLE
Add redox shield

### PR DESCRIPTION
**Pull request by hugo-vrijswijk**
Adds the redox layout with the default keymap from https://config.qmk.fm/#/redox/rev1/LAYOUT. 

The keymap is still a WIP. I need a closer look at the layer modifiers and the raise_layer. I personally don't like the layout much but I figured it is best to stick with the one most users will have by default.

Still a draft because I want to test it out on my own redox as I am sure to have made some mistakes somewhere.

### CODE REVIEW

**Comment by petejohanson** [comment]
@hugo-vrijswijk How is this going? Still a draft?

**Comment by hugo-vrijswijk** [comment]
Hi @petejohanson! Yeah this is still a draft. I can't get it working on my Redox. It's a new board so I am going to see if I can get BlueMicro working on it first, and if I have any hardware problems excluded I will probably come back to this

**Comment by petejohanson** [comment]
> Hi @petejohanson! Yeah this is still a draft. I can't get it working on my Redox. It's a new board so I am going to see if I can get BlueMicro working on it first, and if I have any hardware problems excluded I will probably come back to this

Any luck with this? If not, that's fine, and I can close this for now until you want to return and reopen it.

Thanks!

**Comment by hugo-vrijswijk** [comment]
Yeah, sorry I haven't been able to work on this much. I'll close it and reopen when I have something working 👍

**Comment by hunterwei** [comment]
Hi @hugo-vrijswijk Any progress and luck on this? I am thinking print a batch of Redox with diodes presoldered to use with nice!nano, since I can't find any vendor sell Redox PCB, and getting one from falba.tech shipped from EU is too costly. So before I do that I want to confirm the hardware/PCB design feasibility. Looking forward to your reply.

**Comment by hugo-vrijswijk** [comment]
@hunterwei Hey, thanks for the interest! I haven't really been able to find the time for this project any more unfortunately. I couldn't find any major issues that would suggest Redox support is impossible. But from the PR, I was able to set up a mapping and keymap for all the pins. It _should_ work, but I think I was having connection issues with my Redox and PC/phone.

So I guess I can neither confirm nor deny compatibility 😅. I couldn't find any roadblocks, but I haven't been able to make enough progress to really get something working.

**Pull request closed without merging**
