### PR TITLE
Add general info on tests to run when updating the docker container

### PR DESCRIPTION
**Pull request by mcrosson**
Add some general information on tests to run when updating the Docker container to the documentation testing page.

### CODE REVIEW

**Comment by innovaker** [comment]
Thanks for this @mcrosson.  It's important we have it recorded.

Perhaps we should document this in the zmk-docker project itself?

I feel like we might be able to automate a lot of it into:
https://github.com/zmkfirmware/zmk-docker/blob/main/.github/workflows/containers.yml
Much the same was as I'm hoping to integrate ZMK build/tests into that workflow in the future as it'll save us a lot of manual re-testing whenever the base image is bumped.

What do you think?

**Comment by mcrosson** [comment]
> Perhaps we should document this in the zmk-docker project itself?

I feel like this should be part of the overall docs. There is only one spot for ZMK documentation and I feel like all the documentation should be in one place to facilitate discovery.


> 
> I feel like we might be able to automate a lot of it in:
> https://github.com/zmkfirmware/zmk-docker/blob/main/.github/workflows/containers.yml
> Much the same was as I'm hoping to integrate ZMK build/tests into that workflow in the future as it'll save us a lot of manual re-testing whenever the base image is bumped.
> 
> What do you think?

If it can check run status output against the build information, perhaps. My concern is that running a command just to trap the output for a check may increase container size / screw with caching some.

It may be smarter to do something like `docker run -it --rm /foo/bar` and comparing the output (to whatever degree is least fiddly for verification) IMO.

**Comment by innovaker** [comment]
> If it can check run status output against the build information, perhaps. My concern is that running a command just to trap the output for a check may increase container size / screw with caching some.

I think you misunderstood - nothing in my previous message suggested adding it to the Dockerfile.  I was talking about the GitHub workflow (see link) which could effectively download the container and test each command after the image candidate has been published.

**Comment by mcrosson** [comment]
> I think you misunderstood - nothing in my previous message suggested adding it to the Dockerfile. I was talking about the GitHub workflow (see link) which could effectively download the container and test each command after the image candidate has been published.

I definitely misunderstood. If the commands can be added to the final vetting of the container build that'd be ideal.

**Comment by petejohanson** [comment]
@mcrosson @innovaker With the recent enhancements to the GH actions for `zmkfirmware/zmk-docker`, can this be closed?

**Comment by mcrosson** [comment]
Possibly, I need to defer to @innovaker on this one

**Comment by petejohanson** [comment]
We've automated most of this in the ZMK docker repo at this point. Closing, but feel free to reopen if I missed something. Thanks again!

**Pull request closed without merging**
