### PR TITLE
Added shield for ferris sweep v2

### PR DESCRIPTION
**Pull request by muppetjones**
- [x] Shield is currently working (I'm typing on it now)
- [ ] Add tests
- [ ] Add documentation, etc.

### CODE REVIEW

**Comment by krikun98** [comment]
Don't all the Sweeps work with the `cradio` firmware? That one's in master already.

**Comment by manna-harbour** [comment]
See also https://github.com/davidphilipbarr/zmk-shields/tree/main/sweepv2beta. (@davidphilipbarr )

**Comment by dxmh** [comment]
> Don't all the Sweeps work with the `cradio` firmware? That one's in `main` already.

Correct - the [Cradio shield](https://github.com/zmkfirmware/zmk/tree/main/app/boards/shields/cradio) supports Cradio, Sweep (v1 and v2) and Hypergolic.

**Comment by caksoylar** [comment]
AFAICT the "Q" and "B" positions (D7 and D6 pins) are switched between the [Cradio shield](https://github.com/zmkfirmware/zmk/blob/main/app/boards/shields/cradio/cradio.dtsi) and Sweep v2 (both in this PR and David's [repo](https://github.com/davidphilipbarr/zmk-shields/blob/main/sweepv2beta/sweepv2.dtsi)) or Hypergolic ([here](https://github.com/caksoylar/zmk-config/blob/main/config/boards/shields/hypergolic/hypergolic.dtsi), but it looks the same as v2).

**Comment by dxmh** [comment]
Interesting. My understanding is that Cradio, Sweep and Hypergolic keyboards/PCBs are all designed to use the same Cradio firmware.

FWIW, I use the Cradio shield in `main` for my Sweep v2 and Hypergolic without requiring modifications (except for a [small fix](https://github.com/dxmh/zmk-config/blob/87dca202c5cbd355ae2eb5d895314a8291d5542d/Makefile#L69-L74) to address a hardware issue on my early-revision Sweep v2 PCB).

**Pull request closed without merging**
