### PR TITLE
fix(docs) - updated Windows env setup to windows 11 images

### PR DESCRIPTION
**Pull request by Hello9999901**

### CODE REVIEW

**Comment by joelspadin** [comment]
There's now a Zephyr SDK for Windows. Should we update the documentation to refer to that instead of the GNU ARM embedded toolchain first? You don't need to adjust environment variables when using the Zephyr SDK.

**Comment by Hello9999901** [comment]
Ah I see. Definitely. I am not a Windows user, I just had some time and noticed that the documentation images needed a little DLC. I don't think I am experienced enough to write the documentation for that though.

**Comment by petejohanson** [comment]
> There's now a Zephyr SDK for Windows. Should we update the documentation to refer to that instead of the GNU ARM embedded toolchain first? You don't need to adjust environment variables when using the Zephyr SDK.

I definitely feel we need to do this for Windows *and* macOS, now that the SDK is available for those OSes.

**Comment by Hello9999901** [comment]
I agree too. I will have some more time this week, I will try and write one up for macOS. I'm not very experienced on Windows, so I probably will not be attempting that for the time being.

**Comment by petejohanson** [comment]
Superseded by #1621. Thanks for the work on this regardless!

**Pull request closed without merging**
