### PR TITLE
ci: add dependabot

### PR DESCRIPTION
**Pull request by innovaker**
Checks (daily):
- github-actions
- npm (docs)

@petejohanson, you may also need to configure these settings if you haven't already done so (I don't have access):
https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/about-alerts-for-vulnerable-dependencies#dependabot-alerts-for-vulnerable-dependencies

### CODE REVIEW

**Review by Nicell — APPROVED** [review]
LGTM. Will need to be updated when #568 gets in.

**Comment by innovaker** [comment]
> LGTM. Will need to be updated when #568 gets in.

errrr ... why?  They're unrelated?

**Comment by Nicell** [comment]
> errrr ... why? They're unrelated?

#568 adds NPM packages to the root, so we'd want dependabot to watch there too.

**Comment by innovaker** [comment]
> #568 adds NPM packages to the root, so we'd want dependabot to watch there too.

Good point.  Remind me not to comment on stuff after midnight.

**Review by petejohanson — APPROVED** [review]
Turned on the settings globally for the org.

**Pull request merged**
