### PR TITLE
feat(behaviors): `&key_repeat` behavior + tests.

### PR DESCRIPTION
**Pull request by petejohanson**
* Add new `&key_repeat` behavior that captures and re-sends
  the most recently triggered keycode.

### CODE REVIEW

**Comment by petejohanson** [comment]
Closes #853

**Comment by dxmh** [comment]
Nice @petejohanson!

I have noticed that it doesn't currently repeat keys with modifiers applied:

* `alt`+`left` will only repeat `left`
* `cmd`+`space` will only repeat `space`
* `shift`+`t` will only repeat a lowercase `t`, etc. 

However, it does repeat modified keys when [modifier functions](https://zmk.dev/docs/codes/modifiers/#modifier-functions) are used:

* tap `&kp LG(V)` and it will repeat `cmd`+`v` (paste)
* hold `&kp LGUI`, tap `&kp V` and it will only repeat `v` 
* tap `&sk LGUI`, tap `&kp V` and it will only repeat `v` 

Is this intentional with the current implementation?

**Comment by jcmkk3** [comment]
> Nice @petejohanson!
> 
> I have noticed that it doesn't currently repeat keys with modifiers applied:
> 
> * `alt`+`left` will only repeat `left`
> * `cmd`+`space` will only repeat `space`
> * `shift`+`t` will only repeat a lowercase `t`, etc.
> 
> However, it does repeat modified keys when [modifier functions](https://zmk.dev/docs/codes/modifiers/#modifier-functions) are used:
> 
> * tap `&kp LG(V)` and it will repeat `cmd`+`v` (paste)
> * hold `&kp LGUI`, tap `&kp V` and it will only repeat `v`
> * tap `&sk LGUI`, tap `&kp V` and it will only repeat `v`
> 
> Is this intentional with the current implementation? My initial expectation was that all three of the above scenarios would repeat `cmd`+`v` (paste).

This is a good callout. I was wondering if it would be applied this way or not. One of the reasons that it has always been desirable is to help repeating some mod-based shortcuts that can be a pain to repeat using callum-style mods or at the very least require planning to know that you're going to repeat it. `ctrl-d` for multiple cursors or `ctrl-s` for progressing to the next search candidate in emacs are examples of where I could see using it. I will probably start by putting it on my nav layer, but may later try to incorporate it into the alphas somehow.

**Comment by petejohanson** [comment]
@dxmh @jcmkk3 Please pull the latest and try again. Added code to capture the current mods, along w/ corresponding test case.

**Pull request merged**
