### PR TITLE
Exit setup if no write permissions in directory

### LINKED ISSUE #178: setup.sh: Add check to ensure directory is writable before continuing
Currently, running the `setup.sh` script from a directory doesn't have access to write to causes a semi-cryptic error when it goes to create the local repo directory.

We should add a check earlier in the `docs/static/setup.sh` shell script to verify we can write to the current directory, and if not exit with a helpful error message.

### PR DESCRIPTION
**Pull request by careyk007**
Added a check in `setup.sh` that will print a message and exit if the user does not have write permissions in the current directory. Should close #178.

I haven't ever used powershell, but I would be happy to try something similar if a similar issue exists in Windows.

### CODE REVIEW

**Comment by petejohanson** [comment]
> Added a check in `setup.sh` that will print a message and exit if the user does not have write permissions in the current directory. Should close #178.
> 
> I haven't ever used powershell, but I would be happy to try something similar if a similar issue exists in Windows.  

We should add the check there too, just to be safe. I actually have powershell on my Linux laptop I can use to test.

**Comment by careyk007** [comment]
I took a stab at implementing this for powershell based on an example I found [here](https://www.experts-exchange.com/questions/28071040/PowerShell-how-to-verify-and-set-permissions-on-folder-and-files.html).

**Comment by petejohanson** [comment]
The bash version changes are good, tested and worked as expected here.

@CrossR can you test the PowerShell tweaks? I tried to test using `pwsh` on Linux, but the `Get-Acl` cmdlet is Windows only I have learned.

**Comment by careyk007** [comment]
@petejohanson I was able to successfully test the changes on a Windows machine. Seemed to be working as expected for me, but might still be a good idea to have someone else verify.

**Comment by petejohanson** [comment]
> @petejohanson I was able to successfully test the changes on a Windows machine. Seemed to be working as expected for me, but might still be a good idea to have someone else verify.

You testing works well enough for me. Thanks!

**Review by petejohanson — APPROVED** [review]
Thanks!

**Pull request merged**
