### PR TITLE
feat(docs): add information for testing PRs

### PR DESCRIPTION
**Pull request by BrainWart**
This adds information to the docs in hopes that it will make it easier for testers to test features before they're released. Opinions welcome.

### CODE REVIEW

**Comment by BrainWart** [comment]
There was a brief discussion here: https://discordapp.com/channels/719497620560543766/784523018050469939/816127040729382923

**Comment by okke-formsma** [comment]
west.yml remote add debug (making this findable)

**Comment by okke-formsma** [comment]
I love the contents, not quite sure about the "under development" title. Not sure what it should be. "Beta versions"? "Branches"?

**Comment by petejohanson** [comment]
Love this generally. I'm with @okke-formsma on the naming/location of this. Maybe "Pre-release Features"?

**Review by okke-formsma — APPROVED** [review]
Awesome, thanks!

**Review by okke-formsma — APPROVED** [review]

**Comment by okke-formsma** [comment]
@Nicell @innovaker can one of you merge?

**Review by petejohanson — APPROVED** [review]
Thanks!

**Pull request merged**
