### PR TITLE
Adding Bastyl shield

### PR DESCRIPTION
**Pull request by mseflek**
Adding shield for split keyboard [Bastyl](https://www.hidtech.ca/?product=bastyl).

Tested on my Bastyl with a pair of nice!nano MCUs.

### CODE REVIEW

**Comment by mseflek** [comment]
Just noticed I forgot to update the commented out part of the keycap to reflect the layout. please hold-off on merging until I fix that.

**Review by Nicell — CHANGES_REQUESTED** [review]
Thanks for adding this shield @mseflek! There seems to be a duplicate of each file that has "-checkpoint" in it. Any idea what's up with that? On first glance the "-checkpoint" files look pretty good (minus the naming of course).

**Comment by mseflek** [comment]
> Thanks for adding this shield @mseflek! There seems to be a duplicate of each file that has "-checkpoint" in it. Any idea what's up with that? On first glance the "-checkpoint" files look pretty good (minus the naming of course).

That was my bad -- I typically code for data science so my "IDE" is Jupiter lab. It auto-saves and creates checkpoint files, and I forgot to exclude them from my initial commit before. Thanks for catching. Should be fixed now.

**Comment by noeljee** [comment]
Just finished my Bastyl build. Can’t wait to get the shield up and running!

**Comment by petejohanson** [comment]
Thank you, contributor, for your patience with how long review and merge of boards/shields has taken!

There are three recent refactors/changes to boards and shields that require some attention, and then we can finally get this PR merged!

1. Hardware Metadata
1. Pro Micro shield DT naming changes
1. Split changes for BLE advertising

# Hardware Metadata

## The Problem

When first developing the process around contributing new shields/boards to ZMK, we failed to recognize that several key files (setup scripts, documentation page of supported hardware, and GH Action `build.yml` file) required changes, often in the same spot, for every PR. This resulted in immediate merge conflicts for every *other* PR after one was merged, which is a  headache for contributors.

## The Fix

By adding discrete metadata files that are located with the boards/shields in question, and using that metadata to generate setup scripts, website hardware list, etc., users can contributing new hardware descriptions without the need to change the same files that other contributors are changing.

## Next Steps

First, refer to https://zmk.dev/docs/development/hardware-metadata-files to familiarize yourself with the new metadata file format.

Next, you have two options for fixing up your PR:

1. If comfortable with `git rebase`, perform an interactive rebase and revert any changes to `build.yml`, `hardware.md`, or the setup scripts `setup.sh`/`setup.ps1`, and then add the new metadata YAML file. Then force push your branch. Or,
2. Create a new branch from an up-to-date `main`, copy in the files for your new hardware, add the metadata file, then commit and push the new branch. Then, edit your open PR to point to your new branch.

# Pro Micro shield DT naming changes

In #876, we have simplified the DT naming for the "nexus node" we expose for pro-micro compatible boards, deprecating the use of `pro_micro_a`, and renaming `pro_micro_d` node to simply `pro_micro`. For pro-micro boards and shields, you'll need to adjust your DT to use the proper names.

Please see https://zmk.dev/docs/development/new-shield#shield-overlays for the updated docs on this.

# Split Shield Advertising Changes

In addition, if this is a split PR, please see #658 where we have changed our conventions to *remove* the the name from the right sides, to prevent users attempting to pair with them and causing split sync issues. This also includes removing the " Left" suffix from the naming on the left side. See the changes in that PR for examples of what to change with your split shield.

# Getting Help

If you have any questions about any of these changes, please comment here and tag @zmkfirmware/boards-shields or ask in the `#boards-shields` Discord channel.

**Comment by Nicell** [comment]
Hello! We're closing this PR due to there being no activity since the metadata update to ZMK in September of last year. If you are still interested in updating this PR, please let us know, and we can reopen it and review your changes (hopefully a lot faster this time)!

**Pull request closed without merging**
