### PR TITLE
Fix bug with overlapping combos timeouts

### PR DESCRIPTION
**Pull request by HelloThisIsFlo**
> ### This is a follow-up to #1944 . See the issue for more context.
> This PR fixes the bug mentioned in the issue

## Context

When a timeout fires, the code will filter the remaining combos. Eliminating the one the just timed out, and reordering the remaining ones.

The code _does_ filter the timed out combos correctly, and it does re-order the remaining ones correctly. But! It didn’t clean up properly the position of the very last candidate.

They all move one spot, so when they move, they override the one that was previously there. But the very last combo doesn’t get overridden by anything.

```
Timestamp = 60ms

Before filtering
Combo expires_at=60ms
Combo expires_at=70ms
Combo expires_at=80ms
Combo expires_at=90ms

After filtering
Combo expires_at=70ms
Combo expires_at=80ms
Combo expires_at=90ms
Combo expires_at=90ms <- This extra one is the problem
```

After filtering it returns the number of active candidates. The first time it does it, the number returned is correct, even though this extra entry in `candidates` is not cleaned up.

But then second time it looks at the list, it will return an incorrect number of active candidates. Because of the duplication that happens each time the last candidate is moved up one spot.

## The Bug

When a combo is timing out, the `filter_timed_out_candidates` function is called by `combo_timeout_handler`. 

When a combo times out, we know it’s not going to be activated. The only times when a combo can activate is when a key is pressed (which also calls `filter_timed_out_candidates`).

Since a combo can not be triggered by a timeout, we should only `cleanup()` once **no candidates are remaining.**

However the current code will `cleanup()` if `0 or 1` candidates are remaining. I’m not quite sure why that was implemented this way, maybe it was a quick fix for the issue described above in the context section. Or maybe the idea was that when we have 1 candidate remaining we should clean up. Either way, this was the source of the problem described in #1944 

## Solution

1. Make sure we properly clear out the unused spots in the `candidates` list
2. On timeout, only `cleanup()` if exactly `0 candidates` are left

I also added a test to showcase the proper timeout behavior, and added some debug logging to make this test possible.

I ran all the tests, they all pass ✅

It’s my first PR on this repo, so let me know if if I should update something.

Thanks for this amazing piece of software 😍

### CODE REVIEW

**Comment by HelloThisIsFlo** [comment]
On a sidenote, this PR should conflict with #1387, but maybe it's safer to merge #1387 first. If there's a conflict I'll make sure to update my PR accordingly 👍

**Comment by HelloThisIsFlo** [comment]
Apologies for the failing pre-commit hook. I'll fix that now

**Comment by petejohanson** [comment]
> Apologies for the failing pre-commit hook. I'll fix that now

No worries. For security reasons, PRs from new contributors need approval, so the feedback there can sometimes come "late".

See the docs for setting up pre-commit locally if you are inclined to continue contributing. Thanks for the PR!

**Comment by HelloThisIsFlo** [comment]
That's fair enough. For now it's running on my personal fork, so there's no rush on my side. While it's a very useful fix for me (it allows different timeouts for 1 hand combo vs 2 hand combos), I can see how it's also not affecting a lot of people. So it's not a critical bug at all. Take the time to review it whenever it's approved 👍

I fixed the `pre-commit` issue

**Review by petejohanson — APPROVED** [review]
What a great PR! Thoroughly documented description of both the bug, and the fix, and clean code for the fix, along with accompanying test to boot!

Will merge soon as I see all the tests go green.

Thanks for the fix!

**Comment by HelloThisIsFlo** [comment]
Thank you for your comment 🙏  
I'm happy to contribute to this amazing piece of software 😃

**Pull request merged**
