### PR TITLE
docs: Set netlify node version to lts/*

### PR DESCRIPTION
**Pull request by innovaker**
Prerequisite of #218 and PR #308.

WARNING: UNTESTED.

### CODE REVIEW

**Comment by innovaker** [comment]
The `netlify/zmk/deploy-preview` logs suggest this change switches netlify's node from v10.23.0 to v14.15.0.

This should fix the deployment issue experienced by PR #308.

**Comment by innovaker** [comment]
Switching this into Draft mode because we found this:

https://docs.netlify.com/configure-builds/environment-variables/#declare-variables

which might be the more appropriate way of approaching the issue.

What do you think @petejohanson?

**Comment by petejohanson** [comment]
https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript seems to say either way is totally acceptable. The advantage of the `.nvmrc` is it will be honored for local users of `nvm` as well, which seems to be a win.

**Comment by innovaker** [comment]
If you're happy with it, please merge when ready.

**Pull request merged**
