### PR TITLE
fix(boards): Fix build warnings for Corne-ish Zen builds

### PR DESCRIPTION
**Pull request by caksoylar**
Fixes warnings for two separate issues:
- Missed include for battery header in display widget, after the change in 6f8d080b6 (similar to f71458aca that fixed it for nice!view)
  - Removed no-longer-used BAS header includes
    - Some other files (`nice_view` and stock battery widget) have these as well, but I can't test a build for these. If just making sure they build OK is fine I can add a commit for these too
- Disabled `ZMK_USB` in peripherals (didn't cause a build failure because it was forced off by its dependencies)

### CODE REVIEW

**Comment by petejohanson** [comment]
@caksoylar Mind including the header removal for the others? As long as it still builds (which it should), that should be fine.

**Comment by caksoylar** [comment]
Sure, will push it when I am home in the evening.

**Comment by caksoylar** [comment]
Pushed those too now, `corne_left` and right builds with OLED or nice!views seem to build OK here.

**Review by petejohanson — APPROVED** [review]
Thanks!

**Pull request merged**
