### PR TITLE
Set C_AL_CALC for macOS and iOS to false

### PR DESCRIPTION
**Pull request by bttnns**
Docs update to set C_AL_CALC to false for macOS and iOS

### CODE REVIEW

**Comment by caksoylar** [comment]
Out of curiosity, did you try it with the setting [`CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y`](https://zmk.dev/docs/config/system#hid)? IIRC it was supposed to help with macOS/iOS to consume certain consumer keycodes. Note that you'll need to unpair/repair if you change this setting.

**Comment by bttnns** [comment]
I will try this setting and report back. Thanks!

**Comment by petejohanson** [comment]
> I will try this setting and report back. Thanks!

Any luck?

**Comment by caksoylar** [comment]
@bttnns have you had a chance to test with the setting yet?

**Review by Nick-Munnich — APPROVED** [review]
[Confirmed](https://discord.com/channels/719497620560543766/784523018050469939/1302403583760793711)

**Pull request merged**
