### PR TITLE
Show layer label in display widget.

### PR DESCRIPTION
**Pull request by petejohanson**

### CODE REVIEW

**Comment by Nicell** [comment]
Tested on the left half of my lily58, and it's working well.

Might want some documentation on labels for keymaps. Also we should add label props to existing keymaps.

**Comment by petejohanson** [comment]
> Tested on the left half of my lily58, and it's working well.
> 
> Might want some documentation on labels for keymaps. Also we should add label props to existing keymaps. 

Yeah, both were going to be follow up PRs. Any concerns @Nicell ?

**Comment by Nicell** [comment]
> Yeah, both were going to be follow up PRs. Any concerns @Nicell ?

As long as they're planned for future PRs, I have no concerns. Code looks fine as far as I can tell 👍

**Comment by petejohanson** [comment]
Created #578 and #579 to document those two future items. Merging this one.

**Pull request merged**
