### PR TITLE
Add studio metadata feature

### PR DESCRIPTION
**Pull request by petejohanson**
Add a new `studio` option to the `features` list in our metadata files to indicate the board/shield supports ZMK Studio.

### CODE REVIEW

**Comment by caksoylar** [comment]
Missing keyboards I found:
- `planck_rev6`
- `preonic_rev3`
- `kbdfans_tofu65_v2`
- `contra`
- `m60`
- `boardsource5x12`

**Comment by petejohanson** [comment]
> Missing keyboards I found:
> 
>     * `planck_rev6`
> 
>     * `preonic_rev3`
> 
>     * `kbdfans_tofu65_v2`
> 
>     * `contra`
> 
>     * `m60`
> 
>     * `boardsource5x12`

Thanks. Strictly speaking, the preonic and planck I think need tweaks to enable settings subsystem to fully work with Studio, so I'll skip those for now.

**Comment by Nick-Munnich** [comment]
Add it to the relevant docs page?

**Comment by petejohanson** [comment]
> Add it to the relevant docs page?

Added. Thanks.

**Review by Nick-Munnich — APPROVED** [review]
LGTM

**Pull request merged**
