### PR TITLE
RGB Underglow: Auto off on idle

### PR DESCRIPTION
**Pull request by infused-kim**
This PR adds an auto off on idle feature to the underglow. It's already supported for the backlight and this adds a similar setting to the underglow.

I have tested it on my sofle choc and it's working great.

### CODE REVIEW

**Comment by infused-kim** [comment]
I realized my initial commit had a bug.

`zmk_rgb_underglow_off`and `zmk_rgb_underglow_on` save the state to the config. So if the user has underglow on, then idles  and the underglow is auto-turned off, that setting saved into the flash. If the user turns off and on their keyboard, it starts in the underglow off state even though the user never changed that setting.

The new commit ensures the auto-off feature is only active if the underglow is on and that it doesn't save the temporary off state into the config.

**Comment by ReFil** [comment]
I believe this is a duplicate of my PR #1010

**Comment by ReFil** [comment]
#1010 has been merged so this is superfluous now

**Comment by petejohanson** [comment]
Thanks for the PR, @infused-kim!

Can you please try with the latest main? You'll need to enable the new Kconfig option to enable the functionality.

**Comment by autoferrit** [comment]
This seems like a smaller change. is anything other than review needed to get this in? is there any way I can help? I am new to c/zmk but could try.

**Pull request closed without merging**
