### PR TITLE
feat(keys): Add LSHIFT and RSHIFT aliases

### LINKED ISSUE #783: Add LSHIFT and RSHIFT aliases
Using `LSHIFT` or `RSHIFT` instead of `LSHFT` or `RSHFT` seems to be a recurring error. We should probably add those aliases.

Examples:
* https://discord.com/channels/719497620560543766/719909884769992755/839919783758921788
* https://discord.com/channels/719497620560543766/719909884769992755/807859580327165952
* https://discord.com/channels/719497620560543766/719909884769992755/805518945620721685
* https://discord.com/channels/719497620560543766/719909884769992755/804897080836620338
* https://discord.com/channels/719497620560543766/719909884769992755/829092687725985792
* https://discord.com/channels/719497620560543766/813882537436905552/822175709711302716

### PR DESCRIPTION
**Pull request by dxmh**
Using `LSHIFT` or `RSHIFT` in keymaps (instead of `LSHFT` or `RSHFT`) is a recurring user error. 

This tiny PR resolves #783 by adding `LSHIFT` or `RSHIFT` aliases for those keys.

Update: All documentation has now also been updated to use these new, slightly more intuitive versions.

### CODE REVIEW

**Comment by innovaker** [comment]
Thanks a lot!  Don't forget show the documentation some love too 😄 
Hint: `/zmk/docs/src/data/hid.js`

**Comment by dxmh** [comment]
Thanks @innovaker! I’ve now updated `hid.js` with the aliases. 

Regarding the rest of the documentation, if `LSHFT` and `LSHIFT` are equally valid (i.e. both are aliases of `LEFT_SHIFT`), then perhaps the rest of the docs could continue to use `LSHFT`?

Although, maybe keeping aliases out of the docs/examples could help keep things consistent later down the line — any examples in the docs could be updated now to refer to `LEFT_SHIFT` and `RIGHT_SHIFT` in full, leaving the user to decide to use the shortened variants if they wish?

**Comment by petejohanson** [comment]
> 
> Although, maybe keeping aliases out of the docs/examples could help keep things consistent later down the line — any examples in the docs could be updated now to refer to `LEFT_SHIFT` and `RIGHT_SHIFT` in full, leaving the user to decide to use the shortened variants if they wish?


It's a good question. I would say we should aim for readability for the examples, not necessarily using the "long form" arbitrarily.

If the shorter version is still clear, and also provides an easier to understand example, we should continue to use it.

**Comment by dxmh** [comment]
> If the shorter version is still clear, and also provides an easier to understand example, we should continue to use it.

I like short. 👍 

In https://github.com/zmkfirmware/zmk/issues/783#issuecomment-833861048 @innovaker pointed out that:

> This also throws up the wonderful dilemma of whether we should replace the numerous instances of `LSHFT` and `RSHFT` throughout the documentation (and keymaps).

@petejohanson Do you have any preference as to whether the docs should then stick with`LSHFT`/ `RSHFT` or be updated to use `LSHIFT`/`RSHIFT`?

**Comment by petejohanson** [comment]
> 
> In https://github.com/zmkfirmware/zmk/issues/783#issuecomment-833861048 @innovaker pointed out that:
> 
> > This also throws up the wonderful dilemma of whether we should replace the numerous instances of `LSHFT` and `RSHFT` throughout the documentation (and keymaps).
> 
> @petejohanson Do you have any preference as to whether the docs should then stick with`LSHFT`/ `RSHFT` or be updated to use `LSHIFT`/`RSHIFT`?
> 

I'd say we update it, to use the new, slightly more intuitive version added in this PR.

**Comment by dxmh** [comment]
Thanks @petejohanson - all documentation (including the keymap upgrader) has now been updated to use the slightly more intuitive `LSHIFT` or `RSHIFT` variants added in this PR.

**Review by petejohanson — APPROVED** [review]
Thanks!

**Pull request merged**
