### PR TITLE
Update intro.md

### PR DESCRIPTION
**Pull request by TweetyDaBird**
Added footnote VIA/VIAL

### CODE REVIEW

**Comment by petejohanson** [comment]
You'll need to re-run the npm task to format the doc with prettier after the changes.

**Comment by myst729** [comment]
What do you mean by "fork"? There is official VIA support in QMK, just turn on ENABLE_VIA.

**Comment by petejohanson** [comment]
I'm not that familiar w/ VIA/VIAL, but it sure seems like it works with stock QMK, just requires actually setting up the keyboard properly with it.

**Comment by TweetyDaBird** [comment]
> What do you mean by "fork"? There is official VIA support in QMK, just turn on ENABLE_VIA.

Yes, for VIA the support is integrated into QMK. for VIial though, it needs to be compiled with the Vial fork (make command) as it compiles in modules etc that simply don't exist in QMK's main repository.

**Pull request closed without merging**
