### PR TITLE
Support for C_AC_DESKTOP_SHOW_ALL_APPLICATIONS

### PR DESCRIPTION
**Pull request by shrekale**
I exposed this new key code in keys.h. I tested other two key codes on MacOS, and hence I changed those other two and this new one in the documentation as macos=true.

### CODE REVIEW

**Review by Hello9999901 — COMMENTED** [review]
Looks great! I will approve it once somebody verifies it works on Windows or not.

**Comment by shrekale** [comment]
I'll try to find one Windows PC just to test the codes, I'll comment the results once done.

**Comment by caksoylar** [comment]
You can delete the PR template since that only applies to board/shield PRs. Also did you test `C_AC_SEARCH` and `C_AC_DESKTOP_SHOW_ALL_WINDOWS` and confirmed they work on Mac OS? Asking because you are changing those too and didn't note it.

**Comment by shrekale** [comment]
No I'm changing the documentation for the other two, C_AC_DESKTOP_SHOW_ALL_APPLICATIONS was not exposed in keys.h, which I exposed. All these codes that I changed the documentation for, and the one that I newly exposed, have been tested on Mac OS. linux=true was already there, I added macos=true in the documentation. I don't own a Windows PC, so can't test that. And windows null is rightfully there in the documentation.

**Review by caksoylar — APPROVED** [review]
Looks good to me from a docs perspective.

**Review by shrekale — COMMENTED** [review]
I'm not sure if I have to self review and submit again, but I'm submitting this review again.

**Comment by Hello9999901** [comment]
Hi! Did you verify with a windows computer? If not, it's fine, we can go ahead and merge, just open another PR when you get the time.

**Comment by Hello9999901** [comment]
I agree, I will merge it 😄

**Comment by Hello9999901** [comment]
I'm so sorry, I got busy and forgot. I will merge it now :)

**Review by Hello9999901 — APPROVED** [review]

**Comment by Hello9999901** [comment]
hmm idk if i have the power to fully approve the PR lol

**Review by Hello9999901 — APPROVED** [review]

**Review by petejohanson — APPROVED** [review]
Thanks!

**Comment by petejohanson** [comment]
@shrekale looks like you need to run prettier and clang-format to fix up the formatting of a couple files before this can be merged. See the check results for details.

**Comment by shrekale** [comment]
> @shrekale looks like you need to run prettier and clang-format to fix up the formatting of a couple files before this can be merged. See the check results for details.

Yeah saw that, let me work on it, first time here. You'll get it in one or two days.

**Comment by shrekale** [comment]
I thought this linting and formatting is only an industrial issue. I thought open source folks allow few things a bit rough. Doing it now

**Comment by Hello9999901** [comment]
> I thought this linting and formatting is only an industrial issue. I thought open source folks allow few things a bit rough. Doing it now

Quite the opposite; if you think about it, how are two completely different people, perhaps speaking different languages, supposed to read code without proper formatting and linting? Keep it rough is not an option; it'll only be more off-putting for people who want to contribute.

**Comment by shrekale** [comment]
> > I thought this linting and formatting is only an industrial issue. I thought open source folks allow few things a bit rough. Doing it now
> 
> Quite the opposite; if you think about it, how are two completely different people, perhaps speaking different languages, supposed to read code without proper formatting and linting? Keep it rough is not an option; it'll only be more off-putting for people who want to contribute.

Makes sense. Scrum teams know each other so we know which developer makes what kind of mistakes.

**Comment by shrekale** [comment]
I ran ClangFormat and NPM Prettier commands on the three files I changed. I hope those are the only files that need to be changed here.

**Comment by caksoylar** [comment]
Did you `clang-format` the `docs` files or have some setting off by any chance? The diff is huge now; it seems to have switched the `js` files to 4 space indent from 2 space.

**Review by caksoylar — APPROVED** [review]

**Comment by shrekale** [comment]
I ran CLang format on the js files too. I ran it again only on keys.h which is the one I changed. I ran prettier once again from docs folder. I hope it is now correctly formatted.

**Comment by caksoylar** [comment]
It looks good to me (I had approved a few minutes ago). Once a contributor like Pete approves it will run the automated checks.

**Comment by shrekale** [comment]
Cool. So this is my first contribution in your repo. I'm now going into the rabithole of arduino, IoT and all. Lets see if I can contribute a little more than just keycodes.

**Comment by shrekale** [comment]
Hi, is there any update? It will have conflicts when someone merges new keycodes.

**Review by petejohanson — APPROVED** [review]

**Pull request merged**
