### PR TITLE
Explicitly license documentation as CC-BY-NC-SA.

### PR DESCRIPTION
**Pull request by petejohanson**
Adding an explicit license to our documentation content, using the Creative Commons CC-BY-NC-SA license.

### CODE REVIEW

**Comment by petejohanson** [comment]
I'd like to have the various copyright holders for the docs all weigh in on this, to be sure they are all happy. Checking git logs, I'm hoping to get responses from:

* @careyk007 
* @innovaker 
* @megamind4089 
* @Nicell 
* @Tsquash 
* @kurtis-lew 
* @idan 
* @onebigdoor 
* @chenkevinh 
* @CrossR 
* @okke-formsma 
* @LowNightSnack 
* @BrainWart 
* @Na-Cly 

I know this list is *huge*, but I want to be sure we can get the majority of at least the large contributors if we can before adding an explicit license.

Thanks!

**Comment by idan** [comment]
I consent and approve!

**Comment by kurtis-lew** [comment]
I consent and approve as well!

**Comment by Tsquash** [comment]
I approve :)

**Comment by BrainWart** [comment]
I consent and approve!

**Comment by okke-formsma** [comment]
I approve

**Comment by CrossR** [comment]
I consent and approve!

**Comment by Na-Cly** [comment]
I approve.

**Comment by innovaker** [comment]
I approve.

Will we need headers added to sources also?  Specifically JS(X) etc.?

**Comment by careyk007** [comment]
I approve.

**Comment by petejohanson** [comment]
> I approve.
> 
> Will we need headers added to sources also?  Specifically JS(X) etc.?

Yes, it would be good to add headers. We can file a follow-up issue to add them.

**Comment by LowNightSnack** [comment]
I approve

**Comment by onebigdoor** [comment]
consent and approve (onebigdoor)

**Comment by megamind4089** [comment]
I consent and approve

**Comment by petejohanson** [comment]
@Nicell and @chenkevinh can you weigh in?

**Comment by Nicell** [comment]
I approve

**Comment by chenkevinh** [comment]
I approve.

**Pull request merged**
