### PR TITLE
fix: Properly calculate highest active layer for display.

### PR DESCRIPTION
**Pull request by petejohanson**

### CODE REVIEW

**Comment by caksoylar** [comment]
Is this also changing back the layer name for layer without display-name to returning the integer index?

**Comment by petejohanson** [comment]
> Is this also changing back the layer name for layer without display-name to returning the integer index?

Ok, found a further fix that was required for this. Tested on the nice!view with the stock widget and it now works as expected.

**Comment by saponace** [comment]
This fix worked for me on a corne v2  with nice!view. Thank you @petejohanson !

**Comment by amacleod** [comment]
For the sake of breadcrumbs, https://github.com/zmkfirmware/zmk/pull/2541 addresses #2540

**Pull request merged**
