### PR TITLE
Docs: added mod morph page

### PR DESCRIPTION
**Pull request by measlesbagel**
This is my first pull request and my first time writing documentation so let me know if there's any problems or anything I wrote is unclear.

Created in reference to issue #651

### CODE REVIEW

**Review by okke-formsma — APPROVED** [review]
Thanks! Looks good to me (I think we need another reviewer to merge this)

**Comment by caksoylar** [comment]
Would it be worth mentioning that the seconed keycode would be sent *with* the held modifiers (i.e. the held modifiers are not cleared)?

**Comment by Nicell** [comment]
@caksoylar I think this looks good too, and I agree that adding a part about the fact that held modifiers are also sent and not cleared is an important piece to have in the docs.

**Comment by measlesbagel** [comment]
added a note about how modifiers are sent along with the morphed keypress. hopefully everything looks good now.

**Review by Nicell — APPROVED** [review]
Thanks, @measlesbagel!

**Pull request merged**
