### PR TITLE
feature(split): add split-side encoder support

### PR DESCRIPTION
**Pull request by stephen**
This PR adds support for encoders on the peripheral side. It adds a new characteristic on the GATT service that the central subscribes to.

I only tested this on my own split Kyria.

### CODE REVIEW

**Comment by stephen** [comment]
@petejohanson friendly ping - could you take a look at this when you have some time? i've been happily using it on my kyria split for a couple weeks.

**Comment by smshields** [comment]
I can't comment on the code, but I used this branch successfully on my v1 Sofle; haven't had any issues. I do not have oled or underglow so I can't regression test those.

**Comment by filoxo** [comment]
I was able to use these changes and have tested that the encoder work son the secondary side of my wireless Kyria (with OLEDs). Everything appears to work as expected. The build container does report some warnings due to this code but the build doesn't fail so maybe that's ok?

Screen Shot 2021-04-20 at 6 14 35 PM

**Comment by jamesramsay** [comment]
I've been using without issue on Sofle keyboard - thanks @Stephen ❤️

**Comment by karnadii** [comment]
I have test it with sofle and worked great. thanks

**Comment by rtrajano** [comment]
Didn't work on my BT nice!nano wireless Kyria. I'd test wired but i think it shorts the battery if I attach a TRRS cable.

**Comment by edgelesscorner** [comment]
I have tested this for a month+ on Rollow and it works great. I did need to have both halves encoders on different pin out's, other than that everything works as assumed.

**Comment by yannickjmt** [comment]
Works great on nice!nano Kyria.
Only comment is that my encoders have a different resolution than default. So I put on my .keymap
```
&left_encoder { resolution = <2>; };
&right_encoder { resolution = <2>; };
```
Somehow the &right_encoder parameter was ignored. I had to change the .dtsi file to have desired encoder resolution.

**Comment by rtrajano** [comment]
Are you running this on a wireless nice!nano Kyria setup @yannickjmt ?

I wasn't able to get it working on my wireless nice!nano Kyria and I'm wondering if I did something wrong while building it. 

Thanks for the encoder resolution tip btw, I was wondering why my left encoder took 2 clicks per key press.

> Works great on nice!nano Kyria.
> Only comment is that my encoders have a different resolution than default. So I put on my .keymap
> 
> ```
> &left_encoder { resolution = <2>; };
> &right_encoder { resolution = <2>; };
> ```
> 
> Somehow the &right_encoder parameter was ignored. I had to change the .dtsi file to have desired encoder resolution.

**Comment by yannickjmt** [comment]
> Are you running this on a wireless nice!nano Kyria setup @yannickjmt ?
> 
> I wasn't able to get it working on my wireless nice!nano Kyria and I'm wondering if I did something wrong while building it.
> 
> Thanks for the encoder resolution tip btw, I was wondering why my left encoder took 2 clicks per key press.
> 
Yes, I didn't do anything special, be careful to have the proper bindings, like for example
```
sensor-bindings = <&inc_dec_cp C_VOL_DN C_VOL_UP &inc_dec_cp C_BRI_DN C_BRI_UP>;
sensor-bindings = <&inc_dec_kp PG_UP PG_DN &inc_dec_kp LC(LEFT) LC(RIGHT)>;
```

**Comment by halfurness** [comment]
Amazing work @stephen , I've NEARLY got it working on both sides.
@yannickjmt forgive my ignorance but could you explain your comment about the sensor bindings? You have two lines there, each one using either inc_dec_cp or inc_dec_kp but won't this give you 4 different assignments all at the same time?
What would my sensor bindings be if I wanted left to handle volume and right to handle left/right arrow keys? 
`sensor-bindings = <&inc_dec_kp C_VOL_UP C_VOL_DN &inc_dec_kp LEFT RIGHT>`
or
`sensor-bindings = <&inc_dec_cp C_VOL_UP C_VOL_DN &inc_dec_cp LEFT RIGHT>`

I think I'm not quite getting the difference between CP and KP?

**Comment by yannickjmt** [comment]
> @yannickjmt forgive my ignorance but could you explain your comment about the sensor bindings? You have two lines there, each one using either inc_dec_cp or inc_dec_kp but won't this give you 4 different assignments all at the same time?
Have a look at the doc for the difference between kp and cp, otherwise you can go on the discord, not sure what your second problem is.

**Comment by halfurness** [comment]
Yeah got it all working thanks!

**Comment by jhelvy** [comment]
Working great on my Corne!

**Comment by truonglong88** [comment]
worked well on my Bluetooth Sofle

**Comment by linkdevk** [comment]
I have it working on my Sofle v2. 

When I rotate the encoders, they don't pick up every tick. This an issue for anyone else? 
@truonglong88

**Comment by efyang** [comment]
Working well on my modified ferris sweep! @linkdevk You might have to change your resolution to a lower value, that's what I did and it fixed it.

**Comment by truonglong88** [comment]
> I have it working on my Sofle v2.
> 
> When I rotate the encoders, they don't pick up every tick. This an issue for anyone else?
> @truonglong88

Put this into your keymap file, below `include` codes:
```
&left_encoder { resolution = <1>; };
&right_encoder { resolution = <1>; };
```

**Comment by freznel10** [comment]
I'm tried using this after the latest update and I can't build .

**Comment by linkdevk** [comment]
Did the latest update break it? I know the original developer of this PR is not planning on working on it anymore. RIP dual encoders for now

**Comment by freznel10** [comment]
I get this error when i switch to this PR -- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: 'C:\Program Files\CMake\bin\cmake.EXE' '-DWEST_PYTHON=c:\python39\python.exe' '-BF:\GitHubDesktop\app-2.8.3\zmk\app\build' '-SF:\GitHubDesktop\app-2.8.3\zmk\app' -GNinja -DBOARD=nice_nano -DSHIELD=bone_right

I switch back to main and I could build again

**Comment by caksoylar** [comment]
I rebased this PR (it was a clean rebase) and pushed it to https://github.com/caksoylar/zmk/tree/split-encoder. I don't have a board with encoders but at least one user on Discord reported it working with the Github Actions workflow using https://zmk.dev/docs/features/beta-testing/#testing-features. I'd imagine that building locally would be no different -- it could be an issue with Zephyr version differences if you switched from `main` to this branch.

**Comment by freznel10** [comment]
> Just tested this with a Sofle RGB using nice!nano. Working as intended!

Are you on 2.5?

**Comment by freznel10** [comment]
> I rebased this PR (it was a clean rebase) and pushed it to https://github.com/caksoylar/zmk/tree/split-encoder. I don't have a board with encoders but at least one user on Discord reported it working with the Github Actions workflow using https://zmk.dev/docs/features/beta-testing/#testing-features. I'd imagine that building locally would be no different -- it could be an issue with Zephyr version differences if you switched from `main` to this branch.

Used this and it now works.

**Comment by Necronar** [comment]
> 
> 
> > Just tested this with a Sofle RGB using nice!nano. Working as intended!
> 
> Are you on 2.5?

Yeah. Just forked it yesterday morning.

**Comment by truonglong88** [comment]
Up 😭😭😭

**Comment by AlexCzar** [comment]
Is there something wrong with this PR or is it just the lack of time on the core developers' side?
It has been in limbo since March.

**Comment by clueee** [comment]
don't know why, but i can't use this with Github Actions workflow using https://zmk.dev/docs/features/beta-testing/#testing-features!

**Comment by AlexCzar** [comment]
> don't know why, but i can't use this with Github Actions workflow using https://zmk.dev/docs/features/beta-testing/#testing-features! I'm using sofle rgb!

At the moment this branch has conflicts with the base branch, which means it can't be merged automatically. That is the reason you cannot use it with '...#testing-features'.
If you have enough expertise you can fork it, resolve the conflicts and then use your branch.
It is very sad that this branch was never merged.
I guess the original author lost interest after being ignored for an indefinite time, and reviewers were/are busy and haven't gotten around to it in time.

**Comment by clueee** [comment]
> > don't know why, but i can't use this with Github Actions workflow using https://zmk.dev/docs/features/beta-testing/#testing-features! I'm using sofle rgb!
> 
> At the moment this branch has conflicts with the base branch, which means it can't be merged automatically. That is the reason you cannot use it with '...#testing-features'. If you have enough expertise you can fork it, resolve the conflicts and then use your branch. It is very sad that this branch was never merged. I guess the original author lost interest after being ignored for an indefinite time, and reviewers were/are busy and haven't gotten around to it in time.

So sad to hear that, i'm just an user with a tiny knowledge about coding! Hope someone has enought interest to fix this!

**Comment by AlexCzar** [comment]
I'm on vacation next week and have two encoders on my Kyria, planning to try to do that. I'll comment here if I'm successful.
Not a C dev by a long shot, but hopefully, experience from other languages will help me figure it out ;)

**Comment by ryanjanssen** [comment]
@AlexCzar did you ever have any luck with this?  Thinking of giving it a shot (but i've never touched anything zephyr-based before so I'll have a steep learning curve)

**Comment by AlexCzar** [comment]
@ryanjanssen nope, not yet, and probably not this month :(

**Comment by genkobar** [comment]
> @AlexCzar did you ever have any luck with this? Thinking of giving it a shot (but i've never touched anything zephyr-based before so I'll have a steep learning curve)

I just rebased @stephen's branch onto the current main branch and the base checks succeed... I only tried building for the kyria left and right, which succeeded, but I don't have one so I can't test it out. The GitHub action failed on building for a Kyria with a BlueMicro, but I thought you might want to take a look.

https://github.com/genkobar/zmk/tree/split-encoder

**Comment by ryanjanssen** [comment]
Amazing - I happen to have a kyria (n!n).  I also have the github action failing (using the main zmk repo's github action). when using the following west.yaml:

manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: genkobar
      url-base: https://github.com/genkobar
  projects:
    - name: zmk
      remote: genkobar
      revision: split-encoder
      import: app/west.yml
  self:
    path: config

Is that the correct config? Or should I try building directly from your fork somehow?  (Sorry, I'm not much of an expert in this build process!)
z)

**Comment by genkobar** [comment]
> Is that the correct config? Or should I try building directly from your fork somehow? (Sorry, I'm not much of an expert in this build process!)

I tried doing that build and I discovered a bug that appeared in my code migration process. The codepath with the bug was just not enabled in the test build I did.

That config is correct! I set up a new [zmk-config repo](https://github.com/genkobar/zmkyria-config/runs/4846158510?check_suite_focus=true) to test the github action build process, and it should work for you now.

**Comment by ryanjanssen** [comment]
Thanks!  Same result for me though - peripheral side is not communicating.  Appears to boot because my LEDs turn on briefly, but doesn't respond to any keypresses

**Comment by MNihil** [comment]
> I rebased this PR (it was a clean rebase) and pushed it to https://github.com/caksoylar/zmk/tree/split-encoder. I don't have a board with encoders but at least one user on Discord reported it working with the Github Actions workflow using https://zmk.dev/docs/features/beta-testing/#testing-features. I'd imagine that building locally would be no different -- it could be an issue with Zephyr version differences if you switched from `main` to this branch.

**Thanks @caksoylar, this works for my nice!nano v1 sofle BT.**

I modified my west.yml with the next code if help to someone:

manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
  projects:
    - name: zmk
      remote: caksoylar
      revision: split-encoder
      import: app/west.yml
  self:
    path: config

And I modified the sofle.conf with next config:

# Uncomment the following line to enable the Sofle OLED Display
CONFIG_ZMK_DISPLAY=y

# Uncomment these two lines to add support for encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

**Comment by caksoylar** [comment]
> **Thanks @caksoylar, this works for my sofle nice!nano v1 BT OLED without RGB-LED.**

I should point out that this PR no longer cleanly rebases after 0b0b49d62666cfec2157900fd0dbf62460aa33f9 and I unfortunately don't understand the changes well enough to merge them myself. So my branch will stay rebased on the commit just before the aforementioned one on Nov 1 2021.

**Comment by genkobar** [comment]
> > I rebased this PR (it was a clean rebase) and pushed it to https://github.com/caksoylar/zmk/tree/split-encoder. I don't have a board with encoders but at least one user on Discord reported it working with the Github Actions workflow using https://zmk.dev/docs/features/beta-testing/#testing-features. I'd imagine that building locally would be no different -- it could be an issue with Zephyr version differences if you switched from `main` to this branch.
> 
> **Thanks @caksoylar, this works for my sofle nice!nano v1 BT OLED without RGB-LED.**
> 
> I modified my west.yml with the next code if help to someone:
> 
> ```
> manifest:
>   remotes:
>     - name: zmkfirmware
>       url-base: https://github.com/zmkfirmware
>     - name: caksoylar
>       url-base: https://github.com/caksoylar
>   projects:
>     - name: zmk
>       remote: caksoylar
>       revision: split-encoder
>       import: app/west.yml
>   self:
>     path: config
> ```
> 
> And I modified the sofle.conf with next config:
> 
> ```
> # Uncomment the following line to enable the Sofle OLED Display
> CONFIG_ZMK_DISPLAY=y
> 
> # Uncomment these two lines to add support for encoders
> CONFIG_EC11=y
> CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
> ```

Awesome! It's great that you could provide the west.yml file for others to build with the feature-branch system on GitHub actions. 

I'm trying to find time to get more familiar with the ZMK source code in the next few days, I'll post an update here if I make any progress.

**Comment by clueee** [comment]
> > I rebased this PR (it was a clean rebase) and pushed it to https://github.com/caksoylar/zmk/tree/split-encoder. I don't have a board with encoders but at least one user on Discord reported it working with the Github Actions workflow using https://zmk.dev/docs/features/beta-testing/#testing-features. I'd imagine that building locally would be no different -- it could be an issue with Zephyr version differences if you switched from `main` to this branch.
> 
> **Thanks @caksoylar, this works for my sofle nice!nano v1 BT OLED without RGB-LED.**
> 
> I modified my west.yml with the next code if help to someone:
> 
> ```
> manifest:
>   remotes:
>     - name: zmkfirmware
>       url-base: https://github.com/zmkfirmware
>     - name: caksoylar
>       url-base: https://github.com/caksoylar
>   projects:
>     - name: zmk
>       remote: caksoylar
>       revision: split-encoder
>       import: app/west.yml
>   self:
>     path: config
> ```
> 
> And I modified the sofle.conf with next config:
> 
> ```
> # Uncomment the following line to enable the Sofle OLED Display
> CONFIG_ZMK_DISPLAY=y
> 
> # Uncomment these two lines to add support for encoders
> CONFIG_EC11=y
> CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
> ```

this didn't work on my sofle RGB with mikoto, so sad! github workflow coudn't compile the firmware

**Comment by lewurm** [comment]
Did someone try to rebase this PR on top of this https://github.com/zmkfirmware/zmk/pull/547? It got merged a couple hours ago.

I've tried to do it myself a couple weeks ago but I failed due to not understanding the inner workings of ZMK/Zephyr enough.

**Comment by schmjop** [comment]
@infused-kim thanks a lot for your rebase! Works great so far.

**Comment by lewurm** [comment]
@infused-kim works well on my custom dactyl board. Thank you so much! 🎉

**Comment by JWhitleyWork** [comment]
@infused-kim Looks like the recent upgrade to Zephyr 3.0.0 may have caused some conflicts. Could you possibly rebase again?

@petejohanson It would be great to get this reviewed.

**Comment by infused-kim** [comment]
@JWhitleyWork here you go:
https://github.com/infused-kim/zmk/tree/my-changes/split-encoder

I haven't tested in depth, but it seems to be working well for me. Please let me know if it works or doesn't work for you.

**Comment by hugiselephant** [comment]
I tried @infused-kim 's branch
https://github.com/infused-kim/zmk/tree/my-changes/split-encoder

and it works on my Kyria 2.0 and Nice!Nano 2.0
Thanks so much!

**Comment by yannickjmt** [comment]
Hopefully this will be reviewed before another rebase is necessary.

**Comment by infused-kim** [comment]
> Hopefully this will be reviewed before another rebase is necessary.

I imagine it hasn’t been merged yet, because it implements the feature not in the right way. 

A similar case was for the OLED re-init bug. 

The ZMK team doesn’t want to merge code that will create technical debt. 

I am currently working on a proper version for the oled bug and once that meets merging criteria I will discuss this feature with Pete and see what can be done to get it merged too.

**Comment by MNihil** [comment]
@infused-kim This version doesn't work for me, can you make a test adding a Macro? Thanks!

**Comment by flathopps** [comment]
Hey @infused-kim, I've tried out your branch and found that both encoders do work on my sofle however, both encoders like to do both functions.

For example, if I have one to control the volume and the other to go page up or page down, both of the encoders like to do these actions simultaneously. I have built with `zmkfirmware:main` and the left encoder works fine in that regard. 

Any ideas at all?

**Comment by schadenn** [comment]
@flathopps maybe this helps: https://github.com/MangoIV/zmk/pull/94/files

**Comment by hhharryyyyy** [comment]
@petejohanson @infused-kim can we get this reviewed and merged

**Comment by cankoklu** [comment]
Is this ever going to be merged?

**Comment by LectronPusher** [comment]
I tried to change to this with my new Kyria, and made the changes in [this commit](https://github.com/LectronPusher/zmk-config/commit/d38e8320bdc871a4cfa747d2fcea06452b479e56), and it compiled, but my keymap reverted to some sort of default layout once I loaded the firmware

**Comment by caksoylar** [comment]
> I tried to change to this with my new Kyria, and made the changes in [this commit](https://github.com/LectronPusher/zmk-config/commit/d38e8320bdc871a4cfa747d2fcea06452b479e56), and it compiled, but my keymap reverted to some sort of default layout once I loaded the firmware. Can anyone offer some help?

If you are using Kyria rev2, you might meed to rename your config files to `kyria.*` since that branch might be before the fix for multiple revision shields.

**Comment by LectronPusher** [comment]
> > I tried to change to this with my new Kyria, and made the changes in [this commit](https://github.com/LectronPusher/zmk-config/commit/d38e8320bdc871a4cfa747d2fcea06452b479e56), and it compiled, but my keymap reverted to some sort of default layout once I loaded the firmware. Can anyone offer some help?
> 
> If you are using Kyria rev2, you might meed to rename your config files to `kyria.*` since that branch might be before the fix for multiple revision shields.

Thank you, this worked!

**Comment by CountKeepo** [comment]
This is still waiting to be merged? :(

**Comment by cankoklu** [comment]
It's frustrating that this is still not merged. I'm not too familiar with the process but any information about the reason for the hold up?
it looks like someone just has to approve.

**Review by hhharryyyyy — APPROVED** [review]

**Comment by hhharryyyyy** [comment]
> It's frustrating that this is still not merged. I'm not too familiar with the process but any information about the reason for the hold up? it looks like someone just has to approve.

looks like the zmk owners are not responding. You can probably bug them in discord or something?

**Comment by ValHarlet** [comment]
Hey, how using this branch ?
Modify the west.yml

**Comment by xxvis** [comment]
Would love if this got merged!

**Comment by eegil** [comment]
does not work on kyria rev 3.

**Comment by stevetrofemuk** [comment]
Still waiting...

**Comment by matuck** [comment]
@infused-kim any chance of an updated rebase?

**Comment by infused-kim** [comment]
> @infused-kim any chance of an updated rebase?

Sorry, I switched to a chocofi, which doesn't have encoders and likely won't rebase this as it is quite a lot of work and I won't even able to test it.

**Comment by FrostKiwi** [comment]
We have now a lot of authors having made adjustments to get this working, but it's a bit scattered.
We have:
 - @stephen with this PR, which hasn't seen commits for 2 years. Only the initial with the creation of this PR.
 - https://github.com/infused-kim/zmk/tree/my-changes/split-encoder which worked for a Kyria Rev2, but @infused-kim won't continue because of https://github.com/zmkfirmware/zmk/pull/728#issuecomment-1445389265
 - Minor adjustments by @MangoIV in https://github.com/MangoIV/zmk/pull/94/files
 - @caksoylar Rebasing these changes in a now deleted branch https://github.com/caksoylar/zmk/tree/split-encoder

Can anyone of those involved outline what would have to be done to create a mergable PR from today's main branch? Like a rough 3 step plan of which code segments would have to be integrated in which files?

**Comment by matuck** [comment]
@FrostKiwi I was wondering the same thing.  I also did some searching in discord. From what I read there @petejohanson is doing some refactoring on sensors.  He will not merge this until that is complete.  I imagine once the refactor on sensors is done the things done in these will have to have some work done in them as well.  I don't mind assisting with any help with code on this once he is done with the sensor refactor so it gets merged in.    Until then Im using my own custom repo with fixes from others in for various items.  I would like to see this merged eventually.

**Comment by schmjop** [comment]
Does the fork of infused-kim still work for you guys? I recently made changes to my keymap but now the split-side encoder doesn't work anymore.

**Comment by link6155** [comment]
> Does the fork of infused-kim still work for you guys? I recently made changes to my keymap but now the split-side encoder doesn't work anymore.

Doesn't work for me, the right side with encoder works, but none of the keys on my left side (central) side works

**Comment by DiogoDoreto** [comment]
@schmjop yes, all 4 encoders (2 each side) are working fine in Waterfowl within my branch. Maybe check my [last commit](https://github.com/DiogoDoreto/zmk/commit/fb7c3741ea1906c7743eb6ede9e32b05ff5d23e8) for how I updated the shield files and check whether the equivalent ones for Kyria are set up properly too.

**Comment by JWhitleyWork** [comment]
I have mine working from your branch on a Sofle RGB from Keyhive. However, I noticed that if I set the encoders to `status = "okay"` in the DTSI file, it doesn't work. I have to specifically set them to `disabled` in the DTSI and `okay` in the overlay files.

**Comment by DiogoDoreto** [comment]
> However, I noticed that if I set the encoders to status = "okay" in the DTSI file, it doesn't work. I have to specifically set them to disabled in the DTSI and okay in the overlay files.

Yes, that's how it's described in the docs and I had to do the same change to have my keyboard working.

https://zmk.dev/docs/development/new-shield#encoders

**Comment by FrostKiwi** [comment]
@matuck 
> @FrostKiwi I was wondering the same thing. I also did some searching in discord. From what I read there @petejohanson is doing some refactoring on sensors. He will not merge this until that is complete. I imagine once the refactor on sensors is done the things done in these will have to have some work done in them as well. I don't mind assisting with any help with code on this once he is done with the sensor refactor so it gets merged in. Until then Im using my own custom repo with fixes from others in for various items. I would like to see this merged eventually.

With https://github.com/zmkfirmware/zmk/pull/1499 merged and having read `Sensor refactors for DTS label changes.` as a feature, I inquired. 
@petejohanson mentioned on discord
> That's coming up, yeah, I have some refactors for saner handling of how sensor data/events are handled, that'll make that PR clearer.
Definitely near the top of my list, it's been long requested, yeah.

In case any specific tasks are required I'm sure people in here are happy to help out...

**Comment by matuck** [comment]
@FrostKiwi I did a rebase of the previous work onto the merge.  Had to do a few things to get everything to compile but the encoder on my split is not working.  I will continue to work on it to see if I can get things running.

**Comment by schmjop** [comment]
> @schmjop yes, all 4 encoders (2 each side) are working fine in Waterfowl within my branch. Maybe check my [last commit](https://github.com/DiogoDoreto/zmk/commit/fb7c3741ea1906c7743eb6ede9e32b05ff5d23e8) for how I updated the shield files and check whether the equivalent ones for Kyria are set up properly too.

Thank you for the advice. I just checked and it already seems to be configured correctly both in your fork and the official ZMK repo:
- [kyria_common.dtsi](https://github.com/DiogoDoreto/zmk/blob/waterfowl-encoders/app/boards/shields/kyria/kyria_common.dtsi#L27-L34)
- [kyria_left.overlay](https://github.com/DiogoDoreto/zmk/blob/waterfowl-encoders/app/boards/shields/kyria/kyria_left.overlay#L23)
- [kyria_right.overlay](https://github.com/DiogoDoreto/zmk/blob/waterfowl-encoders/app/boards/shields/kyria/kyria_right.overlay#L32)

Any other ideas?

**Comment by tklzg** [comment]
Rebase work at 2023-04-26 base source.

https://github.com/tklzg/zmk/tree/encoder

If you want to apply the change in the version you are currently using, simply apply infused-kim's patch and  if the build is successful, you can just change the two below.

[app/include/zmk/split/bluetooth/uuid.h]
-#define ZMK_SPLIT_BT_CHAR_SENSOR_STATE_UUID ZMK_BT_SPLIT_UUID(0x00000002)
+#define ZMK_SPLIT_BT_CHAR_SENSOR_STATE_UUID ZMK_BT_SPLIT_UUID(0x00000003)

[app/src/split/bluetooth/service.c]
#if ZMK_KEYMAP_HAS_SENSORS
K_MSGQ_DEFINE(sensor_state_msgq, sizeof(sensor_event),
              CONFIG_ZMK_SPLIT_BLE_PERIPHERAL_POSITION_QUEUE_SIZE, 4);

void send_sensor_state_callback(struct k_work *work) {
    struct sensor_event ev;

    while (k_msgq_get(&sensor_state_msgq, &ev, K_NO_WAIT) == 0) {
-        int err = bt_gatt_notify(NULL, &split_svc.attrs[5], &ev, sizeof(ev));
+       int err = bt_gatt_notify(NULL, &split_svc.attrs[7], &ev, sizeof(ev));
        if (err) {
            LOG_DBG("Error notifying %d", err);
        }
    }
};

**Comment by JulianGodd** [comment]
Works on aurora lily58 with nice!nanov2

Thanks for the fix

**Comment by p3likan0** [comment]
> Rebase work at 2023-04-26 base source.
> 
> https://github.com/tklzg/zmk/tree/encoder
> 
> If you want to apply the change in the version you are currently using, simply apply infused-kim's patch and if the build is successful, you can just change the two below.
> 
> [app/include/zmk/split/bluetooth/uuid.h] -#define ZMK_SPLIT_BT_CHAR_SENSOR_STATE_UUID ZMK_BT_SPLIT_UUID(0x00000002) +#define ZMK_SPLIT_BT_CHAR_SENSOR_STATE_UUID ZMK_BT_SPLIT_UUID(0x00000003)
> 
> [app/src/split/bluetooth/service.c] -int err = bt_gatt_notify(NULL, &split_svc.attrs[5], &ev, sizeof(ev)); +int err = bt_gatt_notify(NULL, &split_svc.attrs[7], &ev, sizeof(ev));

I'm using your fork here: [myrepo](https://github.com/p3likan0/zmk-firmware) with this [commit](https://github.com/p3likan0/zmk-firmware/commit/45f9569cd3ea88187e898cf95cdefd3cfe18cf74) but the right encoder does not work in my sofle v2.

Someone else is facing the same issue?

**Comment by p3likan0** [comment]
> Rebase work at 2023-04-26 base source.
> 
> https://github.com/tklzg/zmk/tree/encoder
> 
> If you want to apply the change in the version you are currently using, simply apply infused-kim's patch and if the build is successful, you can just change the two below.
> 
> [app/include/zmk/split/bluetooth/uuid.h] -#define ZMK_SPLIT_BT_CHAR_SENSOR_STATE_UUID ZMK_BT_SPLIT_UUID(0x00000002) +#define ZMK_SPLIT_BT_CHAR_SENSOR_STATE_UUID ZMK_BT_SPLIT_UUID(0x00000003)
> 
> [app/src/split/bluetooth/service.c] -int err = bt_gatt_notify(NULL, &split_svc.attrs[5], &ev, sizeof(ev)); +int err = bt_gatt_notify(NULL, &split_svc.attrs[7], &ev, sizeof(ev));

I've created an issue here: https://github.com/tklzg/zmk/issues/2
explaining how is not working for me.

Any kind of help here is incredible welcome @tklzg @JulianGodd

**Comment by petejohanson** [comment]
Please everyone test https://github.com/zmkfirmware/zmk/pull/1841 which is updated and is targeted to merge once code reviewed.

**Comment by jaksiri** [comment]
> I have mine working from your branch on a Sofle RGB from Keyhive. However, I noticed that if I set the encoders to `status = "okay"` in the DTSI file, it doesn't work. I have to specifically set them to `disabled` in the DTSI and `okay` in the overlay files.

Could you please share the zmk-config you used for this? I'm trying to get my Keyhive Sofle RGB to work but my right encoder is still not working.

**Comment by petejohanson** [comment]
Closing this since the refactored work was merged into `main` in https://github.com/zmkfirmware/zmk/pull/1841 just now. Thanks @stephen for the original PR!

**Pull request closed without merging**
